import React from 'react';
import { View, ScreenContainer, ScrollView, TouchableOpacity, DecorativeBackground } from '../../design/view';
import { Alert, Platform } from 'react-native';
import { Typography } from '../../components/Typography';
import { Button } from '../../components/Button';
import { Icon } from '../../components/Icon';
import { useTranslation } from 'react-i18next';
import { useAppStore } from '../../storage/store';
import { createParam } from 'solito';
import { useRouter } from 'solito/router';

const { useParam } = createParam<{ generatedPrompt: string; category: string }>();

export function PreviewScreen() {
  const [generatedPrompt] = useParam('generatedPrompt');
  const [category] = useParam('category');
  const { t } = useTranslation();
  const { addPrompt } = useAppStore();
  const { push, back } = useRouter();

  const handleShare = async () => {
    if (Platform.OS === 'web') {
      if (navigator.share) {
        navigator.share({ text: generatedPrompt });
      } else {
        navigator.clipboard.writeText(generatedPrompt || '');
        window.alert('Prompt copied to clipboard!');
      }
    }
  };

  const handleSave = () => {
    if (!generatedPrompt || !category) return;
    addPrompt({
      id: Date.now().toString(),
      category,
      prompt: generatedPrompt,
      createdAt: new Date().toISOString(),
      isFavorite: false,
    });
    if (Platform.OS === 'web') {
      window.alert("Success! Prompt saved to history!");
    } else {
      Alert.alert("Success", "Prompt saved to history!");
    }
    push('/');
  };

  return (
    <ScreenContainer>
      <DecorativeBackground />

      <ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 120 }}>
        <View className="max-w-4xl mx-auto w-full px-4 md:px-6 pt-6 md:pt-10">
          <View className="flex-row items-center mb-8 md:mb-10">
            <TouchableOpacity onPress={() => back()} className="w-10 h-10 md:w-12 md:h-12 bg-surface rounded-xl md:rounded-2xl items-center justify-center border border-white/10 backdrop-blur-md">
               <Icon name="back" size={20} color="#94a3b8" />
            </TouchableOpacity>
            <View className="flex-1 items-center pr-10 md:pr-12">
              <Typography variant="h2" className="text-xl md:text-2xl font-black text-white">
                {t('preview.title')}
              </Typography>
            </View>
          </View>

          <Typography variant="h1" className="mb-6 md:mb-8 text-center text-3xl md:text-4xl font-black text-white px-2">
            {t('preview.subtitle', { defaultValue: 'Ready to use' })}
          </Typography>

          <View className="mb-8 md:mb-12 rounded-3xl md:rounded-4xl border-2 border-primary/20 bg-surface/60 shadow-neon-blue overflow-hidden backdrop-blur-2xl">
            <View className="p-6 md:p-8">
              <Typography className="text-lg md:text-xl leading-[1.6] md:leading-[1.8] text-slate-100 font-medium">
                {generatedPrompt}
              </Typography>
            </View>
            <View className="bg-white/5 px-6 md:px-8 py-3 md:py-4 flex-row justify-between items-center border-t border-white/5">
               <Typography variant="caption" className="text-[10px] md:text-xs text-slate-500 font-bold uppercase tracking-wider">Generated by Promptless</Typography>
               <TouchableOpacity onPress={() => navigator.clipboard.writeText(generatedPrompt || '')}>
                  <Icon name="copy" size={18} color="#3b82f6" />
               </TouchableOpacity>
            </View>
          </View>

          <View className="gap-4 md:gap-5 px-2">
            <Button 
              title={t('preview.save')} 
              onPress={handleSave} 
              className="w-full h-14 md:h-16 bg-primary shadow-neon-blue rounded-2xl md:rounded-3xl" 
              textClassName="text-white text-base md:text-lg"
            />
            <View className="flex-row gap-3 md:gap-4">
              <TouchableOpacity 
                onPress={handleShare}
                className="flex-1 h-14 md:h-16 bg-surface border border-white/10 rounded-2xl md:rounded-3xl items-center justify-center flex-row gap-2 md:gap-3"
              >
                 <Icon name="share" size={18} color="#94a3b8" />
                 <Typography className="text-slate-300 font-bold text-base md:text-lg">{t('preview.share')}</Typography>
              </TouchableOpacity>
              
              <TouchableOpacity 
                onPress={() => back()}
                className="flex-1 h-14 md:h-16 bg-surface border border-white/10 rounded-2xl md:rounded-3xl items-center justify-center flex-row gap-2 md:gap-3"
              >
                 <Icon name="custom" size={18} color="#94a3b8" />
                 <Typography className="text-slate-300 font-bold text-base md:text-lg">{t('preview.edit')}</Typography>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
